# Generated by Django 3.1.7 on 2021-03-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0003_auto_20210303_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inv_Loadings',
            fields=[
                ('loading_week', models.IntegerField(primary_key=True, serialize=False)),
                ('w1_amount', models.IntegerField()),
                ('w2_amount', models.IntegerField()),
                ('w3_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inv_PO',
            fields=[
                ('po_num', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('po_type', models.CharField(choices=[('blanket', 'blanket'), ('std', 'std')], default='blanket', max_length=200)),
                ('po_total', models.IntegerField()),
                ('po_isin', models.BooleanField()),
                ('po_amount', models.IntegerField()),
                ('part_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Inv_Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invchem_month', models.IntegerField()),
                ('chem_isin', models.BooleanField()),
                ('chem_amount', models.IntegerField()),
                ('STD_BOM', models.FloatField()),
                ('expired_date', models.DateTimeField(auto_now_add=True)),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('part_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.chemical')),
            ],
        ),
    ]
