# Generated by Django 3.1.7 on 2021-03-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0004_inv_chemical_inv_loadings_inv_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_chemical',
            name='STD_BOM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inv_chemical',
            name='chem_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inv_chemical',
            name='invchem_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inv_po',
            name='po_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inv_po',
            name='po_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
