# Generated by Django 3.1.7 on 2021-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0006_auto_20210303_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_chemical',
            name='expired_date',
            field=models.DateField(),
        ),
    ]
