# Generated by Django 3.1.7 on 2021-03-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0007_auto_20210303_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical',
            old_name='vendor_id',
            new_name='id',
        ),
    ]
