# Generated by Django 3.1.7 on 2021-03-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0008_auto_20210303_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical',
            old_name='id',
            new_name='vendor_id',
        ),
    ]
