# Generated by Django 3.1.7 on 2021-03-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0009_auto_20210303_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('po_number', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('po_type', models.CharField(choices=[('STD', 'STD'), ('blanket', 'blanket')], default='blanket', max_length=100)),
            ],
            options={
                'ordering': ['po_number'],
            },
        ),
        migrations.CreateModel(
            name='ShowStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROP', models.FloatField(blank=True, null=True)),
                ('max_range', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Chem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chem_status', models.CharField(choices=[('shortage', 'shortage'), ('enough', 'enough'), ('caution', 'caution')], default='enough', max_length=100)),
            ],
            options={
                'ordering': ['chem_status'],
            },
        ),
        migrations.CreateModel(
            name='WeekLoading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('loading', models.IntegerField(blank=True, null=True)),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.package')),
            ],
        ),
        migrations.DeleteModel(
            name='Inv_Loadings',
        ),
        migrations.AlterModelOptions(
            name='chemical',
            options={'ordering': ['part_num']},
        ),
        migrations.RemoveField(
            model_name='inv_chemical',
            name='STD_BOM',
        ),
        migrations.RemoveField(
            model_name='inv_chemical',
            name='invchem_month',
        ),
        migrations.AddField(
            model_name='chemical',
            name='STD_BOM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inv_chemical',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inv_chemical',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Inv_PO',
        ),
        migrations.AddField(
            model_name='status_chem',
            name='chemical',
            field=models.ManyToManyField(to='MRP.Chemical'),
        ),
        migrations.AddField(
            model_name='showstatus',
            name='part_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.chemical'),
        ),
        migrations.AddField(
            model_name='showstatus',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.status_chem'),
        ),
        migrations.AddField(
            model_name='po',
            name='chem',
            field=models.ManyToManyField(to='MRP.Chemical'),
        ),
        migrations.AddField(
            model_name='po',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.vendor'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.po'),
        ),
    ]
