# Generated by Django 3.1.7 on 2021-03-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0010_auto_20210310_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inv_PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_total', models.IntegerField(blank=True, null=True)),
                ('po_isin', models.BooleanField(blank=True, null=True)),
                ('po_amount', models.IntegerField(blank=True, null=True)),
                ('part_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.chemical')),
            ],
        ),
    ]
