# Generated by Django 3.1.7 on 2021-03-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0011_inv_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_po',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.po'),
        ),
    ]
