# Generated by Django 3.1.7 on 2021-03-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0016_inv_chemical_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_chemical',
            name='chem_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
