# Generated by Django 3.1.7 on 2021-03-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0017_auto_20210317_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='chem_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='chem_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='chem_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='leadtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='onhand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='std_packing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='uom',
            field=models.CharField(blank=True, choices=[('litre', 'litre'), ('grams', 'grams'), ('unit', 'unit')], default='litre', max_length=100, null=True),
        ),
    ]
