# Generated by Django 3.1.7 on 2021-03-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0019_auto_20210317_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='part_num',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
