# Generated by Django 3.1.7 on 2021-03-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0020_auto_20210317_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inv_po',
            old_name='part_num',
            new_name='part_num_id',
        ),
    ]
