# Generated by Django 3.1.7 on 2021-03-22 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0021_auto_20210317_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(blank=True, choices=[('TSOP', 'TSOP'), ('LGA', 'LGA')], default='TSOP', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EoqBoq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=30, null=True)),
                ('week', models.CharField(blank=True, max_length=30, null=True)),
                ('loading', models.IntegerField(blank=True, null=True)),
                ('package_iid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.package')),
            ],
        ),
    ]
