# Generated by Django 3.1.7 on 2021-03-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0023_auto_20210322_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
