# Generated by Django 3.1.7 on 2021-03-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0025_auto_20210322_0752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EoqBoq',
            new_name='EoqBoqload',
        ),
    ]
