# Generated by Django 3.1.7 on 2021-04-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0026_auto_20210322_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv_po',
            name='po_total',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_type',
        ),
    ]
