# Generated by Django 3.1.7 on 2021-04-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0027_auto_20210405_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoqboqload',
            name='package_iid',
        ),
        migrations.AlterField(
            model_name='status_chem',
            name='chem_status',
            field=models.CharField(choices=[('shortage', 'shortage'), ('caution', 'caution')], default='enough', max_length=100),
        ),
    ]
