# Generated by Django 3.1.7 on 2021-04-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0028_auto_20210405_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showstatus',
            name='max_range',
        ),
    ]
