# Generated by Django 3.1.7 on 2021-04-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0029_remove_showstatus_max_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_chem',
            name='chem_status',
            field=models.CharField(choices=[('shortage', 'shortage'), ('enough', 'enough')], default='enough', max_length=100),
        ),
    ]
