# Generated by Django 3.1.7 on 2021-04-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MRP', '0030_auto_20210410_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status_chem',
            options={},
        ),
        migrations.RemoveField(
            model_name='status_chem',
            name='chemical',
        ),
        migrations.AddField(
            model_name='status_chem',
            name='listchem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRP.chemical'),
        ),
        migrations.DeleteModel(
            name='ShowStatus',
        ),
    ]
